import type { ComponentType } from 'react';
import type { ToolType } from '../../store';
import type { GeometryIconProps } from './GeometryIcon';
import {
  AllAltitudesToolIcon,
  AltitudeToolIcon,
  AngleMarksToolIcon,
  AngleMarkToolIcon,
  AngleBisectorToolIcon,
  ArcToolIcon,
  AssociatedTriangleToolIcon,
  BoundingBoxToolIcon,
  CanvasClipToolIcon,
  CanvasInitToolIcon,
  CircleCircleIntersectionToolIcon,
  CircleCircleIntersectionTestToolIcon,
  CircleTransformationToolIcon,
  CmToPtConversionToolIcon,
  BarycentricPointToolIcon,
  CircleToolIcon,
  CirclesToolIcon,
  DefinedCircleToolIcon,
  DefinedLineToolIcon,
  DefinedTriangleToolIcon,
  DotProductToolIcon,
  DuplicateSegmentToolIcon,
  EllipseToolIcon,
  EquidistantPointsToolIcon,
  ClipBoundingBoxToolIcon,
  FillAnglesToolIcon,
  FillAngleToolIcon,
  FillCircleToolIcon,
  FillPolygonToolIcon,
  FillSectorToolIcon,
  FindAngleToolIcon,
  FindSlopeAngleToolIcon,
  GoldenRatioPointToolIcon,
  GoldenRectangleToolIcon,
  GetAngleResultToolIcon,
  HarmonicPointToolIcon,
  AutoLabelPointsToolIcon,
  LabelAnglesToolIcon,
  LabelAngleToolIcon,
  LabelArcToolIcon,
  LabelCircleToolIcon,
  LabelLineToolIcon,
  LabelPointsToolIcon,
  LabelPointToolIcon,
  LabelSegmentsToolIcon,
  LabelSegmentToolIcon,
  LengthCalculationToolIcon,
  LineCircleIntersectionToolIcon,
  LineCircleIntersectionTestToolIcon,
  LineIntersectionToolIcon,
  LinesToolIcon,
  LineToolIcon,
  LinearityTestToolIcon,
  MarkArcToolIcon,
  MarkSegmentsToolIcon,
  MarkSegmentToolIcon,
  MidArcPointToolIcon,
  MidpointToolIcon,
  OrthogonalityTestToolIcon,
  PerpendicularBisectorToolIcon,
  PerpendicularToolIcon,
  PermuteTriangleToolIcon,
  PicAngleToolIcon,
  PicRightAngleToolIcon,
  PointCoordinatesToolIcon,
  PointToolIcon,
  PolarPointToolIcon,
  PointOnCircleToolIcon,
  PointOnLineToolIcon,
  PointTransformationToolIcon,
  PointsTransformationToolIcon,
  PowerCircleToolIcon,
  PolygonToolIcon,
  ProjectedExcentersToolIcon,
  ProjectionToolIcon,
  ProtractorToolIcon,
  PtToCmConversionToolIcon,
  PolysegToolIcon,
  ParallelogramToolIcon,
  RadicalAxisToolIcon,
  RandomPointToolIcon,
  RectangleToolIcon,
  RegularPolygonToolIcon,
  SegmentToolIcon,
  SegmentsToolIcon,
  SectorToolIcon,
  SemicircleToolIcon,
  SemicirclesToolIcon,
  RightAngleMarksToolIcon,
  RightAngleMarkToolIcon,
  CompassToolIcon,
  CompassesToolIcon,
  ShowTransformationToolIcon,
  ShowLineConstructionToolIcon,
  SimilitudeCenterToolIcon,
  SquareToolIcon,
  SwapPointsToolIcon,
  TriangleCenterToolIcon,
  VectorPointToolIcon,
  VectorCoordinatesToolIcon,
} from './icons';

export type GeometryIconComponent = ComponentType<GeometryIconProps>;

export const geometryToolIcons: Partial<Record<ToolType, GeometryIconComponent>> = {
  add_point: PointToolIcon,
  add_point_polar: PolarPointToolIcon,
  add_random_point: RandomPointToolIcon,
  add_segment: SegmentToolIcon,
  add_segments: SegmentsToolIcon,
  add_line: LineToolIcon,
  add_lines: LinesToolIcon,
  add_circle: CircleToolIcon,
  add_circles: CirclesToolIcon,
  add_polyseg: PolysegToolIcon,
  add_semicircle: SemicircleToolIcon,
  add_semicircles: SemicirclesToolIcon,
  add_ellipse: EllipseToolIcon,
  add_arc: ArcToolIcon,
  add_sector: SectorToolIcon,
  add_polygon: PolygonToolIcon,
  add_square: SquareToolIcon,
  add_rectangle: RectangleToolIcon,
  add_parallelogram: ParallelogramToolIcon,
  add_golden_rectangle: GoldenRectangleToolIcon,
  add_regular_polygon: RegularPolygonToolIcon,
  add_defined_triangle: DefinedTriangleToolIcon,
  add_altitude: AltitudeToolIcon,
  add_compass: CompassToolIcon,
  add_compasses: CompassesToolIcon,
  add_intersection: LineIntersectionToolIcon,
  fill_circle: FillCircleToolIcon,
  fill_polygon: FillPolygonToolIcon,
  fill_sector: FillSectorToolIcon,
  fill_angle: FillAngleToolIcon,
  fill_angles: FillAnglesToolIcon,
  mark_segment: MarkSegmentToolIcon,
  mark_segments: MarkSegmentsToolIcon,
  mark_arc: MarkArcToolIcon,
  add_angle: AngleMarkToolIcon,
  mark_angles: AngleMarksToolIcon,
  mark_right_angle: RightAngleMarkToolIcon,
  mark_right_angles: RightAngleMarksToolIcon,
  pic_angle: PicAngleToolIcon,
  pic_right_angle: PicRightAngleToolIcon,
  label_point: LabelPointToolIcon,
  label_points: LabelPointsToolIcon,
  auto_label_points: AutoLabelPointsToolIcon,
  label_segment: LabelSegmentToolIcon,
  label_segments: LabelSegmentsToolIcon,
  label_line: LabelLineToolIcon,
  label_angle: LabelAngleToolIcon,
  label_angles: LabelAnglesToolIcon,
  label_circle: LabelCircleToolIcon,
  label_arc: LabelArcToolIcon,
  find_angle: FindAngleToolIcon,
  find_slope_angle: FindSlopeAngleToolIcon,
  get_angle: GetAngleResultToolIcon,
  add_midpoint: MidpointToolIcon,
  add_golden_ratio: GoldenRatioPointToolIcon,
  add_barycentric: BarycentricPointToolIcon,
  add_harmonic: HarmonicPointToolIcon,
  add_equi_points: EquidistantPointsToolIcon,
  add_mid_arc: MidArcPointToolIcon,
  add_point_on_line: PointOnLineToolIcon,
  add_point_on_circle: PointOnCircleToolIcon,
  add_similitude_center: SimilitudeCenterToolIcon,
  add_vector_point: VectorPointToolIcon,
  add_projection: ProjectionToolIcon,
  add_perpendicular: PerpendicularToolIcon,
  add_perpendicular_bisector: PerpendicularBisectorToolIcon,
  add_angle_bisector: AngleBisectorToolIcon,
  add_line_circle_intersection: LineCircleIntersectionToolIcon,
  test_line_circle_intersection: LineCircleIntersectionTestToolIcon,
  add_circle_circle_intersection: CircleCircleIntersectionToolIcon,
  test_circle_circle_intersection: CircleCircleIntersectionTestToolIcon,
  add_radical_axis: RadicalAxisToolIcon,
  show_line_construction: ShowLineConstructionToolIcon,
  add_defined_line: DefinedLineToolIcon,
  add_defined_circle: DefinedCircleToolIcon,
  add_point_transformation: PointTransformationToolIcon,
  add_points_transformation: PointsTransformationToolIcon,
  add_circle_transformation: CircleTransformationToolIcon,
  show_transformation: ShowTransformationToolIcon,
  add_associated_triangle: AssociatedTriangleToolIcon,
  add_permute: PermuteTriangleToolIcon,
  add_duplicate_segment: DuplicateSegmentToolIcon,
  add_protractor: ProtractorToolIcon,
  add_all_altitudes: AllAltitudesToolIcon,
  add_triangle_center: TriangleCenterToolIcon,
  add_projected_excenters: ProjectedExcentersToolIcon,
  is_linear: LinearityTestToolIcon,
  is_ortho: OrthogonalityTestToolIcon,
  dot_product: DotProductToolIcon,
  power_circle: PowerCircleToolIcon,
  get_point_coordinates: PointCoordinatesToolIcon,
  get_vector_coordinates: VectorCoordinatesToolIcon,
  calc_length: LengthCalculationToolIcon,
  pt_to_cm: PtToCmConversionToolIcon,
  cm_to_pt: CmToPtConversionToolIcon,
  swap_points: SwapPointsToolIcon,
  canvas_init: CanvasInitToolIcon,
  canvas_clip: CanvasClipToolIcon,
  show_bounding_box: BoundingBoxToolIcon,
  clip_bounding_box: ClipBoundingBoxToolIcon,
};

export const geometryIconToolIds = Object.keys(geometryToolIcons) as ToolType[];
