import { AstNode } from '../store';

export const getNodeId = (node: AstNode) => {
  switch (node.type) {
    case 'Point': return `point_${node.name}`;
    case 'Segment': return `segment_${node.p1}_${node.p2}`;
    case 'Line': return `line_${node.p1}_${node.p2}`;
    case 'Lines': return `lines_${node.pairs.flat().join('_')}`;
    case 'Segments': return `segments_${node.pairs.flat().join('_')}`;
    case 'PolySeg': return `polyseg_${node.points.join('_')}`;
    case 'Circles': return `circles_${node.pairs.flat().join('_')}`;
    case 'SemiCircle': return `semicircle_${node.center}_${node.radius_point}`;
    case 'SemiCircles': return `semicircles_${node.pairs.flat().join('_')}`;
    case 'Circle': return `circle_${node.center}_${node.radius_point}`;
    case 'Arc': return `arc_${node.center}_${node.first}_${node.second.join('_')}`;
    case 'Sector': return `sector_${node.center}_${node.first}_${node.second.join('_')}`;
    case 'FillCircle': return `fillcircle_${node.center}_${node.radius}`;
    case 'FillPolygon': return `fillpolygon_${node.points.join('_')}`;
    case 'FillSector': return `fillsector_${node.center}_${node.first}_${node.second.join('_')}`;
    case 'FillAngle': return `fillangle_${node.p1}_${node.vertex}_${node.p2}`;
    case 'FillAngles': return `fillangles_${node.angles.flat().join('_')}`;
    case 'CanvasInit': return `canvasinit_${node.xmin}_${node.xmax}_${node.ymin}_${node.ymax}`;
    case 'CanvasClip': return `canvasclip_${node.space}`;
    case 'ShowBoundingBox': return 'showboundingbox';
    case 'StyleSetup': return `stylesetup_${node.kind}`;
    case 'CustomStyle': return `customstyle_${node.name}`;
    case 'Compass': return `compass_${node.center}_${node.through}`;
    case 'Compasses': return `compasses_${node.pairs.flat().join('_')}`;
    case 'ShowLine': return `showline_${node.mode}_${node.points.join('_')}_${node.through ?? 'base'}`;
    case 'ShowTransformation': return `showtransformation_${node.mode}_${node.source}_${node.references.join('_')}`;
    case 'Protractor': return `protractor_${node.origin}_${node.direction}`;
    case 'ClipBoundingBox': return 'clipboundingbox';
    case 'PolygonClip': return `polygonclip_${node.points.join('_')}`;
    case 'CircleClip': return `circleclip_${node.center}_${node.radius_point}`;
    case 'SectorClip': return `sectorclip_${node.center}_${node.first}_${node.second.join('_')}`;
    case 'SegmentMark': return `segmentmark_${node.p1}_${node.p2}`;
    case 'SegmentsMark': return `segmentsmark_${node.pairs.flat().join('_')}`;
    case 'ArcMark': return `arcmark_${node.center}_${node.start}_${node.end}`;
    case 'Ellipse': return `ellipse_${node.center}_${node.x_radius}_${node.y_radius}_${node.angle}`;
    case 'PerpendicularLine': return `perpendicular_${node.p1}_${node.p2}_${node.through}`;
    case 'ProjectionLine': return `projection_${node.p1}_${node.p2}_${node.from}`;
    case 'PerpendicularBisector': return `bisector_${node.p1}_${node.p2}`;
    case 'AngleBisector': return `anglebisector_${node.p1}_${node.vertex}_${node.p2}`;
    case 'TriangleAltitude': return `altitude_${node.side1}_${node.vertex}_${node.side2}`;
    case 'AllAltitudes': return `allaltitudes_${node.p1}_${node.p2}_${node.p3}`;
    case 'AngleMark': return `angle_${node.p1}_${node.vertex}_${node.p2}`;
    case 'AnglesMark': return `anglesmark_${node.angles.flat().join('_')}`;
    case 'RightAngleMark': return `rightanglemark_${node.p1}_${node.vertex}_${node.p2}`;
    case 'RightAnglesMark': return `rightanglesmark_${node.angles.flat().join('_')}`;
    case 'PicAngle': return `picangle_${node.p1}_${node.vertex}_${node.p2}`;
    case 'PicRightAngle': return `picrightangle_${node.p1}_${node.vertex}_${node.p2}`;
    case 'LabelPoint': return `labelpoint_${node.point}`;
    case 'LabelPoints': return `labelpoints_${node.points.join('_')}`;
    case 'AutoLabelPoints': return `autolabelpoints_${node.center ?? 'center'}_${node.points.join('_')}`;
    case 'LabelSegment': return `labelsegment_${node.p1}_${node.p2}`;
    case 'LabelSegments': return `labelsegments_${node.pairs.flat().join('_')}`;
    case 'LabelLine': return `labelline_${node.p1}_${node.p2}`;
    case 'LabelAngle': return `labelangle_${node.p1}_${node.vertex}_${node.p2}`;
    case 'LabelAngles': return `labelangles_${node.angles.flat().join('_')}`;
    case 'LabelCircle': return `labelcircle_${node.center}_${node.radius_point}`;
    case 'LabelArc': return `labelarc_${node.center}_${node.start}_${node.end}`;
    case 'IntersectionPoint': return `intersection_${node.name}`;
    case 'MidPoint': return `midpoint_${node.name}`;
    case 'GoldenRatioPoint': return `goldenratio_${node.name}`;
    case 'BarycentricPoint': return `barycentric_${node.name}`;
    case 'SimilitudeCenter': return `similitude_${node.name}`;
    case 'HarmonicPoint': return `harmonic_${node.name}`;
    case 'HarmonicPair': return `harmonicpair_${node.name1}_${node.name2}`;
    case 'EquiPoints': return `equipoints_${node.name1}_${node.name2}`;
    case 'MidArcPoint': return `midarc_${node.name}`;
    case 'PointOnLine': return `pointonline_${node.name}`;
    case 'PointOnCircle': return `pointoncircle_${node.name}`;
    case 'TriangleCenter': return `trianglecenter_${node.name}`;
    case 'PointTransformation': return `transformation_${node.name}`;
    case 'PointsTransformation': return `transformations_${node.names.join('_')}`;
    case 'VectorPoint': return `vectorpoint_${node.name}`;
    case 'DuplicateSegment': return `duplicatesegment_${node.name}`;
    case 'VectorCoordinates': return `vectorcoords_${node.macro}_${node.p1}_${node.p2}`;
    case 'PointCoordinates': return `pointcoords_${node.macro}_${node.point}`;
    case 'SwapPoints': return `swappoints_${node.p1}_${node.p2}`;
    case 'DefinedLine': return `definedline_${node.results.join('_')}`;
    case 'RadicalAxis': return `radicalaxis_${node.results.join('_')}`;
    case 'DefinedTriangle': return `definedtriangle_${node.name}`;
    case 'AssociatedTriangle': return `associatedtriangle_${node.results.join('_')}`;
    case 'PolygonConstruction': return `polygonconstruction_${node.results.join('_')}`;
    case 'DefinedCircle': return `definedcircle_${node.results.join('_')}`;
    case 'ProjectedExcenters': return `projectedexcenters_${node.results.join('_')}`;
    case 'CircleTransformation': return `circletransformation_${node.results.join('_')}`;
    case 'LineCircleIntersection': return `linecircleintersection_${node.results.join('_')}`;
    case 'LineCircleTest': return `linecircletest_${node.line.join('_')}_${node.circle.join('_')}`;
    case 'CircleCircleIntersection': return `circlecircleintersection_${node.results.join('_')}`;
    case 'CircleCircleTest': return `circlecircletest_${node.circles.flat().join('_')}`;
    case 'LinearityTest': return `linearitytest_${node.points.join('_')}`;
    case 'OrthogonalityTest': return `orthogonalitytest_${node.points.join('_')}`;
    case 'AngleCalculation': return `anglecalculation_${node.mode}_${node.points.join('_')}_${node.macro ?? 'result'}`;
    case 'AngleRetrieval': return `angleretrieval_${node.macro}`;
    case 'LengthCalculation': return `lengthcalculation_${node.p1}_${node.p2}_${node.macro ?? 'result'}`;
    case 'UnitConversion': return `unitconversion_${node.mode}_${node.value}_${node.macro}`;
    case 'DotProduct': return `dotproduct_${node.p1}_${node.p2}_${node.p3}_${node.macro ?? 'result'}`;
    case 'PowerCircle': return `powercircle_${node.point}_${node.center}_${node.radiusPoint}_${node.macro ?? 'result'}`;
    case 'RandomPoint': return `randompoint_${node.name}`;
    case 'Polygon': return `polygon_${node.points.join('_')}`;
    default: return `unknown_${(node as { type?: string }).type ?? 'node'}`;
  }
};
