import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { ScanLine, X } from 'lucide-react';
import { ProjectedExcentersInput } from '../store';

interface Props { open: boolean; pointNames: string[]; onCancel: () => void; onCreate: (input: ProjectedExcentersInput) => void; }

export function ProjectedExcentersDialog({ open, pointNames, onCancel, onCreate }: Props) {
  const [vertices, setVertices] = useState<string[]>([]);
  const [prefix, setPrefix] = useState('J');
  const [suffixes, setSuffixes] = useState(['a', 'b', 'c']);
  const [projections, setProjections] = useState(['X', 'Y', 'Z']);
  const [createExcenters, setCreateExcenters] = useState(true);
  useEffect(() => { if (open) { setVertices([pointNames[0] ?? '', pointNames[1] ?? '', pointNames[2] ?? '']); setPrefix('J'); setSuffixes(['a', 'b', 'c']); setProjections(['X', 'Y', 'Z']); setCreateExcenters(true); } }, [open, pointNames]);
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onCancel(); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onCancel, open]);
  if (!open) return null;
  const validName = (value: string) => /^[A-Za-z][A-Za-z0-9_]*$/.test(value.trim());
  const validation = pointNames.length < 3 ? 'Add at least three points.' : new Set(vertices).size !== 3 ? 'Choose three distinct triangle vertices.' : !validName(prefix) || [...suffixes, ...projections].some(value => !validName(value)) ? 'Names must start with a Latin letter.' : null;
  const pointSelect = (label: string, index: number) => <label className="property-field-label text-slate-400">{label}<select value={vertices[index]} onChange={event => setVertices(current => current.map((value, i) => i === index ? event.target.value : value))} className="property-input mt-1.5 bg-slate-950 font-mono text-slate-100">{pointNames.map(point => <option key={point}>{point}</option>)}</select></label>;
  const nameInputs = (labels: string[], values: string[], setter: (values: string[]) => void) => labels.map((label, index) => <label key={label} className="property-field-label text-slate-400">{label}<input aria-label={label} value={values[index]} onChange={event => setter(values.map((value, i) => i === index ? event.target.value : value))} className="property-input mt-1.5 bg-slate-950 font-mono text-slate-100" /></label>);
  return createPortal(<div className="theme-dialog-backdrop fixed inset-0 z-[100] flex items-center justify-center p-6 backdrop-blur-sm" onMouseDown={onCancel}><section role="dialog" aria-modal="true" aria-labelledby="projected-excenters-title" className="theme-dialog w-full max-w-2xl overflow-hidden rounded-2xl border shadow-2xl shadow-black/30" onMouseDown={event => event.stopPropagation()}><header className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-500/15 text-orange-300"><ScanLine size={18} /></span><div><h2 id="projected-excenters-title" className="text-sm font-semibold">Project excenters</h2><p className="mt-0.5 text-[11px] text-slate-500">Create all nine perpendicular projections with \tkzDefProjExcenter.</p></div></div><button onClick={onCancel} className="h-8 w-8 rounded-lg text-slate-500 hover:bg-white/10" aria-label="Close projected excenters dialog"><X size={16} className="mx-auto" /></button></header><div className="space-y-4 p-5"><div className="grid grid-cols-3 gap-3">{pointSelect('Vertex A', 0)}{pointSelect('Vertex B', 1)}{pointSelect('Vertex C', 2)}</div><div className="grid grid-cols-4 gap-3"><label className="property-field-label text-slate-400">Excenter prefix<input aria-label="Excenter prefix" value={prefix} onChange={event => setPrefix(event.target.value)} className="property-input mt-1.5 bg-slate-950 font-mono text-slate-100" /></label>{nameInputs(['Excenter suffix 1', 'Excenter suffix 2', 'Excenter suffix 3'], suffixes, setSuffixes)}</div><div className="grid grid-cols-3 gap-3">{nameInputs(['Projection prefix 1', 'Projection prefix 2', 'Projection prefix 3'], projections, setProjections)}</div><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={createExcenters} onChange={event => setCreateExcenters(event.target.checked)} className="h-4 w-4 accent-orange-500" /> Define the three excenters first</label><p className="text-[11px] text-slate-500">Creates {projections.flatMap(projection => suffixes.map(suffix => `${projection}${suffix}`)).join(', ')}.</p>{validation && <div className="rounded-xl border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-xs text-amber-200">{validation}</div>}</div><footer className="flex justify-end gap-2 border-t border-white/10 bg-slate-950/30 px-5 py-4"><button onClick={onCancel} className="h-9 px-3 text-xs font-semibold text-slate-400">Cancel</button><button disabled={Boolean(validation)} onClick={() => onCreate({ p1: vertices[0], p2: vertices[1], p3: vertices[2], namePrefix: prefix.trim(), excenterSuffixes: suffixes.map(value => value.trim()), projectionPrefixes: projections.map(value => value.trim()), createExcenters })} className="h-9 rounded-lg bg-orange-600 px-4 text-xs font-semibold text-white disabled:opacity-40">Create projections</button></footer></section></div>, document.body);
}
